[database]
    conn = "host=localhost port=8157 user=tcc_tourism password=tcc_tourism dbname=tcc_tobatourism_tourism sslmode=disable"
    connAuth = "host=localhost port=8157 user=tcc_tourism password=tcc_tourism dbname=tcc_tourism_auth sslmode=disable"
